project:
  type: website

website:
  title: "Portafolio Davin Diaz"
  navbar:
  
    left:
      - href: index.qmd
        text: Inicio
      - href: projects.qmd
        text: Proyectos
      - href: resume.qmd
        text: Curriculum
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

